### ISSUE TITLE
LoggingIn and question about Meteor.userId()

### ISSUE THREAD

**Issue by dbismut** [thereactivestack/meteor-react-router-ssr#51] opened 2016-04-11 22:54 UTC
Hey @eXon, I was browsing through the code of FlowRouter SSR and noticed that Arunoda is also having:

```javascript
Meteor.loggingIn = () => {
  return false;
};
```

Which I think could be a useful addition on react-router-ssr.

Also, I was wondering why you need these lines:

```javascript
 Meteor.userId = () => context.userId;
 Meteor.user = () => undefined;
```

I don't think FlowRouter is doing the same hence my question. Sorry if this is obvious...

**Comment by dbismut** [comment] 2016-04-11 23:04
Answering my own question sorry: obviously I guess you need to define userId since it wouldn't be available outside of methods on the server. However, should we have `Meteor.user = () => Meteor.users.findOne(context.userId)` then? That would ensure Meteor.user() work on the server the same way it does on the client?

**Comment by john-osullivan** [comment] 2016-04-15 01:30
I just came here to try and report a bug based on this!  Lots of my rendering logic depends on Meteor.user().  If it doesn't behave according to the Meteor spec when rendering on the server, then everything breaks down.  @dbismut , did you try adding your fix and seeing if it worked?

**Comment by john-osullivan** [comment] 2016-04-15 01:37
At a bare minimum, if the assumption is that the user can't be logged in when rendering on the server, then setting `Meteor.user() = null;` would preserve intended behavior.

**Comment by dbismut** [comment] 2016-04-15 13:16
Hi @john-osullivan, no I didn't try the fix just yet. I'm storing `Meteor.users.findOne(Meteor.userId())` in a redux store at the moment.

**Comment by eXon** [comment] 2016-05-01 03:03
The reason why it is done this way is because the first render on the client is working this way (as far as I can remember). If you already had the user, your HTML would differ from the client HTML and React would notice the difference and re-render everything. Let me know if I'm wrong.

**Comment by eXon** [comment] 2016-05-07 18:12
This is fixed on master. Now `Meteor.user()` should be the right value.

**Closed by eXon** 2016-05-07 18:12 UTC
