### ISSUE TITLE
Support for low-level publish API

### ISSUE THREAD

**Issue by imkost** [thereactivestack/meteor-react-router-ssr#16] opened 2015-11-08 19:58 UTC
`meteor-react-router-ssr` does not support `this.added`, `this.changed`, `this.removed`, `this.ready` and `this.onStop` functions

http://docs.meteor.com/#/full/meteor_publish (see example section)

P.S. probably FastRender's issue

**Comment by eXon** [comment] 2015-11-08 21:26
Those functions are going to be easy to stub. Wasn't really aware of that but I agree they are important to support.

**Comment by eXon** [comment] 2015-11-09 01:23
Stubs have been added. SSR should work fine no matter what now.

**Comment by imkost** [comment] 2015-11-10 00:29
I'm not sure it will work.

Let's imagine application where users can create notes. Also users can protect some of their notes with additional password (every note can have password). Password is kept as a raw string, but should never be sent to client. Nevertheless client should know if category has password (is locked) or does not.

```javascript
const Notes = new Mongo.Collection('notes')
```

Every note has this structure:

```javascript
note = {
  ownerId: {String},
  text: {String},
  password: {String}, optional
}
```

How to tell make client know that note is locked without publishing a password?

#### Solution 1

Create additional property `isLocked` and update it every time `password` is updated. Then just don't sent `password` field to client.

```javascript
Meteor.publish('userNotes', function() {
  return Notes.find(
    { ownerId: this.userId },
    { fields: { password: -1 } }
  );
});
```

#### Solution 2

Use low-level API:

```javascript
function removePassword(fields) {
  if (fields.password) {
    delete fields.password;
    fields.isLocked = true;
  }
}

Meteor.publish('userNotes', function() {
  const handle = Categories.find({ ownerId: this.userId }).observeChanges({
    added: (id, fields) => {
      removePassword(fields);
      this.added('notes', id, fields);
    },

    changed: (id, fields) => {
      removePassword(fields);
      this.changed('notes', id, fields);
    },
  });

  this.ready();
  this.onStop(() => handle.stop());
});
```

This is a more verbose solution and is hard to understand if you are not familiar with this API, but it is very powerful. You have full control on what data to sent and how to process this data.

So I'm not sure that `noop` function helps here.

Anyway, I have error during ssr:

```
W20151110-03:10:17.380(3)? (STDERR) error while server-rendering TypeError: Cannot read property '_cursorDescription' of undefined
W20151110-03:10:17.380(3)? (STDERR)     at Function.Mongo.Collection._fakePublish (lib/server.jsx:266:24)
W20151110-03:10:17.380(3)? (STDERR)     at Object.Meteor.subscribe (lib/server.jsx:81:32)
W20151110-03:10:17.380(3)? (STDERR)     at n.a.value (webpack:///:6529:1)
W20151110-03:10:17.380(3)? (STDERR)     at MeteorDataManager.calculateData (meteor-data-mixin.jsx:62:24)
W20151110-03:10:17.381(3)? (STDERR)     at n.ReactMeteorData.componentWillMount (meteor-data-mixin.jsx:5:45)
W20151110-03:10:17.381(3)? (STDERR)     at n.<anonymous> (webpack:///:7475:1)
W20151110-03:10:17.381(3)? (STDERR)     at n.<anonymous> (webpack:///:7475:1)
W20151110-03:10:17.381(3)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (../../../../../Projects/locknote/website/react/lib/ReactCompositeComponent:210:1)
W20151110-03:10:17.381(3)? (STDERR)     at Object.ReactReconciler.mountComponent (../../../../../Projects/myapp/react/lib/ReactReconciler:37:1)
W20151110-03:10:17.381(3)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (../../../../../Projects/myapp/react/lib/ReactCompositeComponent:225:1)
```

The code in Solution 1 works, the code in Solution 2 crashes with this error.

**Comment by eXon** [comment] 2015-11-10 10:54
I'll have to investigate more to see what we can do about it

**Comment by imkost** [comment] 2015-11-10 11:55
FastRender supports low-level publish API, but I'm not sure if this is helpful for ssr.

Check out https://github.com/kadirahq/fast-render/blob/master/lib/server/publish_context.js

**Comment by minfawang** [comment] 2015-11-17 07:04
Ah I'm getting the same error and I'm not using the lower level publication. I basically just tried to redo the kickstart-hugeapp repo. I believe this error reproduction repo will provide value to your investigation:

https://github.com/minfawang/ReactRouterSSR-error-reproduce/tree/master

**Comment by eXon** [comment] 2015-11-18 02:52
@minfawang It should be fixed in the last version.

@imkost Can you let me know if this is working with the last version? Do you have a repo I can clone to reproduce the bug?

**Comment by minfawang** [comment] 2015-11-18 03:37
@eXon Thanks for the latest commits. I updated the packages with the latest commits (`webpack@0.3.4` and `react-router-ssr@0.3.5`), but the error didn't go away. (Note the error happens only when running in production mode and when every time a user tries to access the page.)

**Comment by eXon** [comment] 2015-11-18 11:57
@minfawang I've cloned your project, did meteor update and meteor --production and it works for me. Have you tried clearing .meteor/local?

**Comment by minfawang** [comment] 2015-11-18 18:14
@eXon Oh I didn't clear the `.meteor/local` folder. Now everything works perfectly. Awesome!

**Comment by eXon** [comment] 2015-12-13 16:25
Not sure if this is still an issue. I'll close it for now.

**Comment by ribbedcrown** [comment] 2015-12-30 12:37
it seems the issue persists at `reactrouter:react-router-ssr@1.1.0`. When I've tried to work with [tmeasday:publish-counts](https://atmospherejs.com/tmeasday/publish-counts) (it uses low-level publish api) I've got this error:

``` shell
W20151230-18:02:54.789(6)? (STDERR) error while server-rendering TypeError: Object [object Object] has no method 'added'
W20151230-18:02:54.789(6)? (STDERR)     at Object.Counts.publish (packages/tmeasday_publish-counts/server/publish-counts.js:79:1)
W20151230-18:02:54.790(6)? (STDERR)     at Context.<anonymous> (webpack:///XXXXXX/.meteor/local/webpack-npm/~/react/lib/ReactDOMComponent.js:678:1)
W20151230-18:02:54.790(6)? (STDERR)     at Object.subscribe (lib/server.jsx:223:66)
W20151230-18:02:54.790(6)? (STDERR)     at t.l.value (webpack:///XXXXXX/.meteor/local/webpack-npm/~/react/lib/ReactDOMComponent.js:575:1)
W20151230-18:02:54.790(6)? (STDERR)     at MeteorDataManager.calculateData (meteor-data-mixin.jsx:61:24)
W20151230-18:02:54.790(6)? (STDERR)     at t.ReactMeteorData.componentWillMount (meteor-data-mixin.jsx:5:45)
W20151230-18:02:54.790(6)? (STDERR)     at t.<anonymous> (webpack:///XXXXXX/.meteor/local/webpack-npm/~/react/lib/ReactDOMFactories.js:109:1)
W20151230-18:02:54.790(6)? (STDERR)     at t.<anonymous> (webpack:///XXXXXX/.meteor/local/webpack-npm/~/react/lib/ReactDOMComponent.js:960:1)
W20151230-18:02:54.790(6)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (../../../../../XXXXXX/react/lib/ReactCompositeComponent:210:1)
W20151230-18:02:54.791(6)? (STDERR)     at Object.ReactReconciler.mountComponent (../../../../../XXXXXX/react/lib/ReactReconciler:37:1)

```
Similar errors I had at ssr with [reywood:publish-composite](https://atmospherejs.com/reywood/publish-composite).

I'll make reproduction repo after NY holidays.

**Comment by eXon** [comment] 2015-12-30 14:33
It seems like it is a context problem rather than a low level api error. I'll take a look.

**Comment by ribbedcrown** [comment] 2015-12-30 14:40
@eXon thank you for a quick response!

**Comment by yched** [comment] 2015-12-31 14:52
Concur - using reywood:publish-composite too, and seeing the same `error while server-rendering TypeError: Object [object Object] has no method 'added'` error

**Comment by eXon** [comment] 2016-01-03 03:00
Fixed in 1.2.0

The SSR part faking the publish behavior has been completely rewritten to support better all those low-level API + publish-counts. Everything should work without an error now.

Unfortunally for publish-composite, it is not working yet with fast-render because ready() is triggered before the data is loaded. You can use another library that do the same thing or follow https://github.com/englue/meteor-publish-composite/issues/67

**Closed by eXon** 2016-01-03 03:00 UTC

**Comment by yched** [comment] 2016-01-04 09:18
@eXon : awesome :-)

In the same spirit, I opened PR #27 to support subscribe()'s onReady callback

**Comment by yched** [comment] 2016-01-04 09:56
So yeah, regarding reywood:publish-composite, https://github.com/englue/meteor-publish-composite/issues/67 is an issue for SSR since it currently marks the subscription as ready as soon as the data for the "primary" cursor is sent, and data for the "secondary/joined" cursors get sent after that.

I'm not sure whether it's the only issue though : trying to use the latest meteor-react-router-ssr with reywood:publish-composite, I'm seeing no data at all in the server-side subscription, even on the primary cursor

**Comment by ribbedcrown** [comment] 2016-01-05 10:46
@eXon Great! It works like a charm.
